//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminler
    {
        public byte adminID { get; set; }
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telefon { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
