//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankalar
    {
        public short bankaID { get; set; }
        public string bankaAdi { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string sube { get; set; }
        public string iban { get; set; }
        public string hesapNo { get; set; }
        public string yetkili { get; set; }
        public string telefon { get; set; }
        public string hesapTuru { get; set; }
        public string tarih { get; set; }
        public Nullable<short> firmaId { get; set; }
        public Nullable<bool> bankaDurum { get; set; }
    
        public virtual firmalar firmalar { get; set; }
    }
}
