//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class faturaIcerik
    {
        public int faturaIcerikID { get; set; }
        public Nullable<int> urunAdi { get; set; }
        public Nullable<short> miktar { get; set; }
        public Nullable<decimal> birimFiyat { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<int> faturaBilgiId { get; set; }
        public Nullable<bool> faturaIcerikdurum { get; set; }
    
        public virtual faturaBilgi faturaBilgi { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
