//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class faturaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public faturaBilgi()
        {
            this.faturaIcerik = new HashSet<faturaIcerik>();
        }
    
        public int faturaBilgiID { get; set; }
        public string SeriSiraNo { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public string vergiDairsei { get; set; }
        public string alici { get; set; }
        public Nullable<byte> teslimEden { get; set; }
        public Nullable<int> teslimAlan { get; set; }
        public Nullable<bool> faturaBilgiDurum { get; set; }
    
        public virtual musteriler musteriler { get; set; }
        public virtual personeller personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faturaIcerik> faturaIcerik { get; set; }
    }
}
