//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class giderler
    {
        public int giderID { get; set; }
        public string ay { get; set; }
        public string yil { get; set; }
        public Nullable<decimal> elektrik { get; set; }
        public Nullable<decimal> su { get; set; }
        public Nullable<decimal> dogalGaz { get; set; }
        public Nullable<decimal> internet { get; set; }
        public Nullable<decimal> maaslar { get; set; }
        public Nullable<decimal> ekstra { get; set; }
        public string notlar { get; set; }
    }
}
