//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ticariOtomasyonProjeEntities : DbContext
    {
        public ticariOtomasyonProjeEntities()
            : base("name=ticariOtomasyonProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminler> adminler { get; set; }
        public virtual DbSet<bankalar> bankalar { get; set; }
        public virtual DbSet<departmanlar> departmanlar { get; set; }
        public virtual DbSet<faturaBilgi> faturaBilgi { get; set; }
        public virtual DbSet<faturaIcerik> faturaIcerik { get; set; }
        public virtual DbSet<firmalar> firmalar { get; set; }
        public virtual DbSet<giderler> giderler { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<sanatcilar> sanatcilar { get; set; }
        public virtual DbSet<satinAlma> satinAlma { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<vergiDaireleri> vergiDaireleri { get; set; }
    
        public virtual ObjectResult<bankaBilgileri_Result> bankaBilgileri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bankaBilgileri_Result>("bankaBilgileri");
        }
    
        public virtual int musteriHareketler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("musteriHareketler");
        }
    
        public virtual int musteriHareketler2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("musteriHareketler2");
        }
    
        public virtual ObjectResult<string> enFazlaUrunluSanatci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enFazlaUrunluSanatci");
        }
    
        public virtual ObjectResult<string> enFazlaUrunluKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enFazlaUrunluKategori");
        }
    
        public virtual ObjectResult<string> enFazlaMusteriliIl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("enFazlaMusteriliIl");
        }
    
        public virtual ObjectResult<vergiDaireleriVeFaturalar_Result> vergiDaireleriVeFaturalar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiDaireleriVeFaturalar_Result>("vergiDaireleriVeFaturalar");
        }
    }
}
