//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class satinAlma
    {
        public int satinAlmaID { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<byte> sanatciId { get; set; }
        public Nullable<short> firmaId { get; set; }
    
        public virtual firmalar firmalar { get; set; }
        public virtual sanatcilar sanatcilar { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
