//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLmuzikDunyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.faturaIcerik = new HashSet<faturaIcerik>();
            this.satinAlma = new HashSet<satinAlma>();
            this.satislar = new HashSet<satislar>();
        }
    
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public Nullable<byte> sanatci { get; set; }
        public string yil { get; set; }
        public Nullable<short> adet { get; set; }
        public Nullable<decimal> alisFiyat { get; set; }
        public Nullable<decimal> satisFiyat { get; set; }
        public string detay { get; set; }
        public string urunGorsel { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<bool> urunDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faturaIcerik> faturaIcerik { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        public virtual sanatcilar sanatcilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satinAlma> satinAlma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satislar> satislar { get; set; }
    }
}
